export interface TriviaQuestion {
  id: number;
  category: string;
  question: string;
  answer: string;
}

export const PRESET_QUESTIONS: TriviaQuestion[] = [
  // ALLGEMEINWISSEN (1-80)
  { id: 1, category: "Allgemeinwissen", question: "Welches Edelmetall hat das chemische Symbol Au?", answer: "Gold" },
  { id: 2, category: "Allgemeinwissen", question: "In welcher deutschen Stadt steht das Brandenburger Tor?", answer: "Berlin" },
  { id: 3, category: "Allgemeinwissen", question: "Wie viele Planeten hat unser Sonnensystem?", answer: "8" },
  { id: 4, category: "Allgemeinwissen", question: "Wer schrieb das Drama 'Faust'?", answer: "Johann Wolfgang von Goethe" },
  { id: 5, category: "Allgemeinwissen", question: "Aus welchem Land stammt die Automarke Fiat?", answer: "Italien" },
  { id: 6, category: "Allgemeinwissen", question: "Was ist das größte Organ des menschlichen Körpers?", answer: "Die Haut" },
  { id: 7, category: "Allgemeinwissen", question: "In welchem Jahr fiel die Berliner Mauer?", answer: "1989" },
  { id: 8, category: "Allgemeinwissen", question: "Wie viele Zähne hat ein erwachsener Mensch normalerweise (ohne Weisheitszähne)?", answer: "28" },
  { id: 9, category: "Allgemeinwissen", question: "Welches Land hat die größte Bevölkerung der Welt?", answer: "Indien" },
  { id: 10, category: "Allgemeinwissen", question: "Was ist das chemische Symbol für Wasser?", answer: "H2O" },
  { id: 11, category: "Allgemeinwissen", question: "Wie nennt man ein Dreieck, bei dem alle drei Seiten gleich lang sind?", answer: "Gleichseitiges Dreieck" },
  { id: 12, category: "Allgemeinwissen", question: "Wer gilt als Erfinder der Buchdruckerkunst?", answer: "Johannes Gutenberg" },
  { id: 13, category: "Allgemeinwissen", question: "Wie heißt das flüssige Gestein im Inneren der Erde?", answer: "Magma" },
  { id: 14, category: "Allgemeinwissen", question: "Aus welchem Land stammen die Olympischen Spiele der Antike?", answer: "Griechenland" },
  { id: 15, category: "Allgemeinwissen", question: "In welchem Ozean liegt die Insel Madagaskar?", answer: "Indischer Ozean" },
  { id: 16, category: "Allgemeinwissen", question: "Welches Gas macht den größten Teil unserer Atemluft aus?", answer: "Stickstoff" },
  { id: 17, category: "Allgemeinwissen", question: "Wer malte das berühmte Gemälde 'Mona Lisa'?", answer: "Leonardo da Vinci" },
  { id: 18, category: "Allgemeinwissen", question: "Welcher Fluss fließt durch Ägypten?", answer: "Nil" },
  { id: 19, category: "Allgemeinwissen", question: "Wie viele Bundesländer hat Deutschland?", answer: "16" },
  { id: 20, category: "Allgemeinwissen", question: "Welcher Planet ist der Sonne am nächsten?", answer: "Merkur" },
  { id: 21, category: "Allgemeinwissen", question: "Wer war der erste Mensch auf dem Mond?", answer: "Neil Armstrong" },
  { id: 22, category: "Allgemeinwissen", question: "Welches Tier ist das größte lebende Säugetier?", answer: "Blauwal" },
  { id: 23, category: "Allgemeinwissen", question: "Welches Land ist flächenmäßig das größte der Erde?", answer: "Russland" },
  { id: 24, category: "Allgemeinwissen", question: "Welches Organ im menschlichen Körper reinigt das Blut und produziert Urin?", answer: "Niere" },
  { id: 25, category: "Allgemeinwissen", question: "In welcher Stadt befindet sich der Eiffelturm?", answer: "Paris" },
  { id: 26, category: "Allgemeinwissen", question: "Welche Himmelsrichtung liegt gegenüber von Osten?", answer: "Westen" },
  { id: 27, category: "Allgemeinwissen", question: "Welcher Vogel kann nicht fliegen, aber hervorragend schwimmen und lebt am Südpol?", answer: "Pinguin" },
  { id: 28, category: "Allgemeinwissen", question: "Wie viele Knochen hat das Skelett eines erwachsenen Menschen ungefähr?", answer: "Ca. 206" },
  { id: 29, category: "Allgemeinwissen", question: "Was ist die Hauptstadt von Spanien?", answer: "Madrid" },
  { id: 30, category: "Allgemeinwissen", question: "Welches Instrument erfand Bartolomeo Cristofori?", answer: "Klavier" },
  { id: 31, category: "Allgemeinwissen", question: "Was ist die Währung von Japan?", answer: "Yen" },
  { id: 32, category: "Allgemeinwissen", question: "Wie viele Minuten hat ein Tag?", answer: "1440" },
  { id: 33, category: "Allgemeinwissen", question: "Welche Farbe erhält man, wenn man Blau und Gelb mischt?", answer: "Grün" },
  { id: 34, category: "Allgemeinwissen", question: "Wer entwickelte die Relativitätstheorie?", answer: "Albert Einstein" },
  { id: 35, category: "Allgemeinwissen", question: "In welchem Jahr begann der Erste Weltkrieg?", answer: "1914" },
  { id: 36, category: "Allgemeinwissen", question: "Welcher Kontinent ist fast vollständig von Eis bedeckt?", answer: "Antarktika" },
  { id: 37, category: "Allgemeinwissen", question: "Aus welcher Pflanze wird Schokolade hergestellt?", answer: "Kakaobaum (Kakao)" },
  { id: 38, category: "Allgemeinwissen", question: "Wie heißt die Hauptstadt von Italien?", answer: "Rom" },
  { id: 39, category: "Allgemeinwissen", question: "Wer schrieb das Buch 'Die unendliche Geschichte'?", answer: "Michael Ende" },
  { id: 40, category: "Allgemeinwissen", question: "Wie lautet die chemische Formel für Kochsalz?", answer: "NaCl (Natriumchlorid)" },
  { id: 41, category: "Allgemeinwissen", question: "Welcher Ozean ist der tiefste der Welt?", answer: "Pazifischer Ozean" },
  { id: 42, category: "Allgemeinwissen", question: "In welchem Land stehen die Pyramiden von Gizeh?", answer: "Ägypten" },
  { id: 43, category: "Allgemeinwissen", question: "Welcher Feiertag wird am 31. Oktober gefeiert?", answer: "Halloween (Reformationstag)" },
  { id: 44, category: "Allgemeinwissen", question: "Wie viele Herzen hat ein Krake?", answer: "3" },
  { id: 45, category: "Allgemeinwissen", question: "Was ist das härteste natürliche Material auf der Erde?", answer: "Diamant" },
  { id: 46, category: "Allgemeinwissen", question: "Welches Land schenkte den USA die Freiheitsstatue?", answer: "Frankreich" },
  { id: 47, category: "Allgemeinwissen", question: "Wie viele Tage hat ein Schaltjahr?", answer: "366" },
  { id: 48, category: "Allgemeinwissen", question: "In welcher Sprache wurde die 'Odyssee' ursprünglich verfasst?", answer: "Altgriechisch" },
  { id: 49, category: "Allgemeinwissen", question: "Wer war der erste Bundeskanzler der Bundesrepublik Deutschland?", answer: "Konrad Adenauer" },
  { id: 50, category: "Allgemeinwissen", question: "Wie heißt das höchste Gebäude der Welt?", answer: "Burj Khalifa" },
  { id: 51, category: "Allgemeinwissen", question: "Welche Frucht hat die Samen auf der Außenseite?", answer: "Erdbeere" },
  { id: 52, category: "Allgemeinwissen", question: "Was ist die Hauptstadt von Australien?", answer: "Canberra" },
  { id: 53, category: "Allgemeinwissen", question: "Aus welchem Land stammt der berühmte Physiker Nikola Tesla?", answer: "Kroatien (damals Kaisertum Österreich)" },
  { id: 54, category: "Allgemeinwissen", question: "Wie viele Bundesländer hat Österreich?", answer: "9" },
  { id: 55, category: "Allgemeinwissen", question: "Was transportieren Arterien im menschlichen Körper hauptsächlich?", answer: "Sauerstoffreiches Blut" },
  { id: 56, category: "Allgemeinwissen", question: "Welche dänische Firma ist weltberühmt für ihre bunten Klemmbausteine?", answer: "LEGO" },
  { id: 57, category: "Allgemeinwissen", question: "Welches Gebirge trennt Europa und Asien?", answer: "Ural" },
  { id: 58, category: "Allgemeinwissen", question: "In welchem Jahr sank die Titanic?", answer: "1912" },
  { id: 59, category: "Allgemeinwissen", question: "Wer gilt als Vater der Psychoanalyse?", answer: "Sigmund Freud" },
  { id: 60, category: "Allgemeinwissen", question: "Wie nennt man die Lehre von den Pilzen?", answer: "Mykologie" },
  { id: 61, category: "Allgemeinwissen", question: "Welcher Baum verliert im Winter seine Nadeln?", answer: "Lärche" },
  { id: 62, category: "Allgemeinwissen", question: "Aus welchem Land stammt das Gericht Sushi?", answer: "Japan" },
  { id: 63, category: "Allgemeinwissen", question: "Was ist die Hauptstadt der Schweiz?", answer: "Bern" },
  { id: 64, category: "Allgemeinwissen", question: "Wie viele Saiten hat eine klassische Gitarre üblicherweise?", answer: "6" },
  { id: 65, category: "Allgemeinwissen", question: "Welches Land hat die Landesvorwahl +41?", answer: "Schweiz" },
  { id: 66, category: "Allgemeinwissen", question: "In welchem Land liegt die Ruinenstadt Machu Picchu?", answer: "Peru" },
  { id: 67, category: "Allgemeinwissen", question: "Wer erfand das Dynamit?", answer: "Alfred Nobel" },
  { id: 68, category: "Allgemeinwissen", question: "Welches Vitamin stellt der Körper mithilfe von Sonnenlicht selbst her?", answer: "Vitamin D" },
  { id: 69, category: "Allgemeinwissen", question: "Wie heißt der kleinste Staat der Erde?", answer: "Vatikanstadt" },
  { id: 70, category: "Allgemeinwissen", question: "In welchem Meer liegt die Insel Mallorca?", answer: "Mittelmeer" },
  { id: 71, category: "Allgemeinwissen", question: "Wie viele Farben hat ein Regenbogen?", answer: "7" },
  { id: 72, category: "Allgemeinwissen", question: "Welches Land ist bekannt für den Eistee 'Bubble Tea'?", answer: "Taiwan" },
  { id: 73, category: "Allgemeinwissen", question: "Aus wie vielen Spielern besteht eine Fußballmannschaft auf dem Feld?", answer: "11" },
  { id: 74, category: "Allgemeinwissen", question: "Wer malte 'Die Erschaffung Adams' an der Decke der Sixtinischen Kapelle?", answer: "Michelangelo" },
  { id: 75, category: "Allgemeinwissen", question: "Was ist die Hauptstadt von Portugal?", answer: "Lissabon" },
  { id: 76, category: "Allgemeinwissen", question: "Wie viele Kontinente gibt es auf der Erde?", answer: "7" },
  { id: 77, category: "Allgemeinwissen", question: "Welches Insekt produziert Honig?", answer: "Biene" },
  { id: 78, category: "Allgemeinwissen", question: "In welchem Jahr endete der Zweite Weltkrieg?", answer: "1945" },
  { id: 79, category: "Allgemeinwissen", question: "Wie heißt der längste Fluss Deutschlands?", answer: "Rhein" },
  { id: 80, category: "Allgemeinwissen", question: "Welche Sprache wird in Brasilien am meisten gesprochen?", answer: "Portugiesisch" },

  // POPKULTUR (81-160)
  { id: 81, category: "Popkultur", question: "Welche britische Band sang den Hit 'Yellow Submarine'?", answer: "The Beatles" },
  { id: 82, category: "Popkultur", question: "Welche fiktive Stadt wird von Batman beschützt?", answer: "Gotham City" },
  { id: 83, category: "Popkultur", question: "Wer ist der Hauptdarsteller in der Filmreihe 'Pirates of the Caribbean'?", answer: "Johnny Depp" },
  { id: 84, category: "Popkultur", question: "Welches Haustier besitzt Garfield im berühmten Comic?", answer: "Odie (Hund) / Pooky (Teddy)" },
  { id: 85, category: "Popkultur", question: "Wie heißt der König der Löwen im gleichnamigen Disney-Klassiker?", answer: "Simba (oder Mufasa)" },
  { id: 86, category: "Popkultur", question: "Wie viele Filme umfasst die Herr-der-Ringe-Haupttrilogie?", answer: "3" },
  { id: 87, category: "Popkultur", question: "Aus welcher Serie stammt das berühmte Zitat 'Winter is coming'?", answer: "Game of Thrones" },
  { id: 88, category: "Popkultur", question: "Wer ist der Schöpfer der Star-Wars-Saga?", answer: "George Lucas" },
  { id: 89, category: "Popkultur", question: "Welcher Popstar singt den Hit 'Bad Romance'?", answer: "Lady Gaga" },
  { id: 90, category: "Popkultur", question: "Wie heißt die rothaarige Hauptfigur in Disneys 'Die kleine Meerjungfrau'?", answer: "Arielle" },
  { id: 91, category: "Popkultur", question: "Welcher Schauspieler spielte Iron Man im Marvel Cinematic Universe?", answer: "Robert Downey Jr." },
  { id: 92, category: "Popkultur", question: "Welche Farbe hat die Haut von Shrek?", answer: "Grün" },
  { id: 93, category: "Popkultur", question: "Welches berühmte Lied von Queen fängt mit 'Is this the real life?' an?", answer: "Bohemian Rhapsody" },
  { id: 94, category: "Popkultur", question: "Wer ist das berühmteste Maskottchen von Walt Disney?", answer: "Micky Maus" },
  { id: 95, category: "Popkultur", question: "Welcher Sänger wird als 'King of Pop' bezeichnet?", answer: "Michael Jackson" },
  { id: 96, category: "Popkultur", question: "Aus welchem Land stammt das Phänomen 'K-Pop'?", answer: "Südkorea" },
  { id: 97, category: "Popkultur", question: "Wie heißt der junge Zauberer mit der blitzförmigen Narbe auf der Stirn?", answer: "Harry Potter" },
  { id: 98, category: "Popkultur", question: "Wer spielt die Rolle des Captain Jack Sparrow?", answer: "Johnny Depp" },
  { id: 99, category: "Popkultur", question: "Welche US-amerikanische Sitcom dreht sich um sechs Freunde in New York, darunter Ross und Rachel?", answer: "Friends" },
  { id: 100, category: "Popkultur", question: "In welcher Zeichentrickserie wohnt ein Schwamm in einer Ananas unter dem Meer?", answer: "SpongeBob Schwammkopf" },
  { id: 101, category: "Popkultur", question: "Welches Lied von Psy brach 2012 alle YouTube-Rekorde?", answer: "Gangnam Style" },
  { id: 102, category: "Popkultur", question: "Welcher berühmte Archäologe trägt stets eine Peitsche und einen Fedorajahut?", answer: "Indiana Jones" },
  { id: 103, category: "Popkultur", question: "Wie heißt der Butler von Batman?", answer: "Alfred (Pennyworth)" },
  { id: 104, category: "Popkultur", question: "Welches Lied von Luis Fonsi und Daddy Yankee wurde 2017 zum weltweiten Sommerhit?", answer: "Despacito" },
  { id: 105, category: "Popkultur", question: "Welcher Film von James Cameron aus dem Jahr 2009 zeigt blauhäutige Wesen auf dem Mond Pandora?", answer: "Avatar" },
  { id: 106, category: "Popkultur", question: "In welchem Film spielt Keanu Reeves die Figur Neo?", answer: "Matrix" },
  { id: 107, category: "Popkultur", question: "Wie heißt das Eichhörnchen aus den 'Ice Age'-Filmen, das ständig eine Eichel jagt?", answer: "Scrat" },
  { id: 108, category: "Popkultur", question: "Welcher US-Rapper nannte sich früher 'The Real Slim Shady'?", answer: "Eminem" },
  { id: 109, category: "Popkultur", question: "Wie heißt die fiktive Welt, in der die Romane von J.R.R. Tolkien spielen?", answer: "Mittelerde" },
  { id: 110, category: "Popkultur", question: "Welches Tier ist Meister Splinter in den 'Teenage Mutant Ninja Turtles'?", answer: "Ratte" },
  { id: 111, category: "Popkultur", question: "Welche Sängerin ist für ihre extrem treue Fanbase namens 'Swifties' bekannt?", answer: "Taylor Swift" },
  { id: 112, category: "Popkultur", question: "Aus welchem Science-Fiction-Film stammt die Zeile: 'Möge die Macht mit dir sein'?", answer: "Star Wars" },
  { id: 113, category: "Popkultur", question: "Welche schwedische Band gewann 1974 den Eurovision Song Contest mit 'Waterloo'?", answer: "ABBA" },
  { id: 114, category: "Popkultur", question: "Welcher Superheld wird durch den Biss einer radioaktiven Spinne erschaffen?", answer: "Spider-Man" },
  { id: 115, category: "Popkultur", question: "In welchem Horrorfilm treibt eine besessene Puppe namens Chucky ihr Unwesen?", answer: "Chucky - Die Mörderpuppe" },
  { id: 116, category: "Popkultur", question: "Wie heißt das Raumschiff von Han Solo in Star Wars?", answer: "Millennium Falke (Millennium Falcon)" },
  { id: 117, category: "Popkultur", question: "Welche Serie handelt von einer Gruppe Teenager, die im fiktiven Hawkins gegen das 'Upside Down' kämpfen?", answer: "Stranger Things" },
  { id: 118, category: "Popkultur", question: "Welches Auto dient in 'Zurück in die Zukunft' als Zeitmaschine?", answer: "DeLorean" },
  { id: 119, category: "Popkultur", question: "Welcher Schauspieler verkörperte den legendären Joker in 'The Dark Knight'?", answer: "Heath Ledger" },
  { id: 120, category: "Popkultur", question: "Wie heißt das gelbe Haustier von Ash Ketchum in Pokémon?", answer: "Pikachu" },
  { id: 121, category: "Popkultur", question: "Welcher Agent arbeitet unter der Nummer 007?", answer: "James Bond" },
  { id: 122, category: "Popkultur", question: "Welcher legendäre Musiker schrieb und sang den Song 'Imagine'?", answer: "John Lennon" },
  { id: 123, category: "Popkultur", question: "Wie heißt die älteste Tochter der Simpsons-Familie?", answer: "Lisa" },
  { id: 124, category: "Popkultur", question: "Welche Sängerin wurde als die 'Queen of Pop' berühmt und sang 'Like a Virgin'?", answer: "Madonna" },
  { id: 125, category: "Popkultur", question: "Welche Filmreihe basiert auf einem Spielzeug von Hasbro über außerirdische, sich transformierende Roboter?", answer: "Transformers" },
  { id: 126, category: "Popkultur", question: "Wie heißt die skurrile, gothic-begeisterte Tochter aus der Addams Family?", answer: "Wednesday" },
  { id: 127, category: "Popkultur", question: "Welche Zeichentrick-Familie wohnt in der Stadt Springfield?", answer: "Die Simpsons" },
  { id: 128, category: "Popkultur", question: "Aus welchem Film stammt das ikonische Zitat: 'Ich sehe tote Menschen'?", answer: "The Sixth Sense" },
  { id: 129, category: "Popkultur", question: "Welcher Schauspieler spielte die Hauptrolle im Film 'Forrest Gump'?", answer: "Tom Hanks" },
  { id: 130, category: "Popkultur", question: "Wie heißt der mürrische grüne Weihnachtshasser, erfunden von Dr. Seuss?", answer: "Grinch" },
  { id: 131, category: "Popkultur", question: "Welche Girlgroup sang 1996 den Hit 'Wannabe'?", answer: "Spice Girls" },
  { id: 132, category: "Popkultur", question: "Wer schuf das berühmte Comic-Universum um Spider-Man, Iron Man und Thor?", answer: "Stan Lee" },
  { id: 133, category: "Popkultur", question: "Welcher Disney-Film handelt von zwei Schwestern namens Elsa und Anna?", answer: "Die Eiskönigin (Frozen)" },
  { id: 134, category: "Popkultur", question: "Wie heißt das Fabelwesen im Film 'Shrek', das stottert, nervt, aber sehr loyal ist?", answer: "Esel" },
  { id: 135, category: "Popkultur", question: "In welcher Netflix-Serie geht es um tödliche Kinderspiele in Südkorea?", answer: "Squid Game" },
  { id: 136, category: "Popkultur", question: "Welche Band sang den Welthit 'Smells Like Teen Spirit'?", answer: "Nirvana" },
  { id: 137, category: "Popkultur", question: "Wer verkörperte die Hauptrolle der Katniss Everdeen in 'Die Tribute von Panem'?", answer: "Jennifer Lawrence" },
  { id: 138, category: "Popkultur", question: "Wie heißt der fiktive magische Kontinent aus der Witcher-Saga?", answer: "Der Kontinent" },
  { id: 139, category: "Popkultur", question: "Welcher Schauspieler spielte Neo in Matrix und John Wick?", answer: "Keanu Reeves" },
  { id: 140, category: "Popkultur", question: "Welche legendäre US-Zeichentrick-Band wurde von Damon Albarn und Jamie Hewlett gegründet?", answer: "Gorillaz" },
  { id: 141, category: "Popkultur", question: "Wie heißt die kleine schlaue Elfe aus Peter Pan?", answer: "TinkerBell" },
  { id: 142, category: "Popkultur", question: "Welcher Sänger landete einen Mega-Hit mit 'Shape of You'?", answer: "Ed Sheeran" },
  { id: 143, category: "Popkultur", question: "In welchem Film bricht eine Gruppe von Wissenschaftlern auf, um Geister in New York zu fangen?", answer: "Ghostbusters" },
  { id: 144, category: "Popkultur", question: "Welche Romanreihe handelt von Vampiren im fiktiven Ort Forks (Bella und Edward)?", answer: "Twilight" },
  { id: 145, category: "Popkultur", question: "Welcher Schauspieler spielte Jack Dawson im Welthit Titanic?", answer: "Leonardo DiCaprio" },
  { id: 146, category: "Popkultur", question: "Wie heißt der fliegende Hund bzw. Drache im Film 'Die unendliche Geschichte'?", answer: "Fuchur" },
  { id: 147, category: "Popkultur", question: "Welches Lied von Whitney Houston wurde durch den Film 'Bodyguard' weltberühmt?", answer: "I Will Always Love You" },
  { id: 148, category: "Popkultur", question: "Wie heißt der exzentrische Besitzer der Schokoladenfabrik bei Roald Dahl?", answer: "Willy Wonka" },
  { id: 149, category: "Popkultur", question: "Welche Sitcom handelt von einem Physik-Duo namens Sheldon und Leonard?", answer: "The Big Bang Theory" },
  { id: 150, category: "Popkultur", question: "Welches Fabeltier ist das Wappentier des Hauses Gryffindor in Harry Potter?", answer: "Löwe" },
  { id: 151, category: "Popkultur", question: "Welcher Musiker sang 'Purple Rain'?", answer: "Prince" },
  { id: 152, category: "Popkultur", question: "Aus welcher Musikgruppe ging Justin Timberlake hervor?", answer: "*NSYNC" },
  { id: 153, category: "Popkultur", question: "In welcher Zeichentrick-Serie jagen sich eine graue Katze und eine braune Maus?", answer: "Tom und Jerry" },
  { id: 154, category: "Popkultur", question: "Welche US-Zeichentrickserie parodiert die amerikanische Gesellschaft mit Charakteren wie Eric Cartman und Stan Marsh?", answer: "South Park" },
  { id: 155, category: "Popkultur", question: "Welche K-Pop Band feierte mit 'Dynamite' und 'Butter' internationale Charterfolge?", answer: "BTS" },
  { id: 156, category: "Popkultur", question: "Wie heißt der berühmte Drache aus der unendlichen Geschichte?", answer: "Fuchur" },
  { id: 157, category: "Popkultur", question: "Welche fiktive Spielshow steht im Mittelpunkt der Buchreihe 'Die Tribute von Panem'?", answer: "Hungerspiele (Hunger Games)" },
  { id: 158, category: "Popkultur", question: "Welches Wesen ist Gollum in der Herr-der-Ringe-Saga, bevor er den Ring fand?", answer: "Hobbit (Smeagol)" },
  { id: 159, category: "Popkultur", question: "Welche berühmte britische Sängerin schuf das Album '21' mit dem Hit 'Rolling in the Deep'?", answer: "Adele" },
  { id: 160, category: "Popkultur", question: "In welchem Film verwandelt sich ein reicher Unternehmer nachts in einen Fledermaus-Rächer?", answer: "Batman" },

  // GEOGRAFIE (161-240)
  { id: 161, category: "Geografie", question: "Was ist der flächenmäßig zweitgrößte Staat der Erde?", answer: "Kanada" },
  { id: 162, category: "Geografie", question: "In welchem Gebirge liegt der Mount Everest?", answer: "Himalaya" },
  { id: 163, category: "Geografie", question: "Wie heißt das kleinste Bundesland Deutschlands?", answer: "Bremen" },
  { id: 164, category: "Geografie", question: "Welcher Fluss fließt durch London?", answer: "Themse" },
  { id: 165, category: "Geografie", question: "Welcher Vulkan zerstörte im Jahr 79 n. Chr. die Stadt Pompeji?", answer: "Vesuv" },
  { id: 166, category: "Geografie", question: "Wie heißt der größte See der Welt nach Fläche (der kein Süßwassersee ist)?", answer: "Kaspisches Meer" },
  { id: 167, category: "Geografie", question: "Zu welchem Staat gehört die Insel Grönland?", answer: "Dänemark" },
  { id: 168, category: "Geografie", question: "Was ist die Hauptstadt von Neuseeland?", answer: "Wellington" },
  { id: 169, category: "Geografie", question: "Welches Meer trennt Europa von Afrika?", answer: "Mittelmeer" },
  { id: 170, category: "Geografie", question: "Welcher Fluss ist der wasserreichste Fluss der Erde?", answer: "Amazonas" },
  { id: 171, category: "Geografie", question: "In welchem US-Bundesstaat liegt die Wüstenstadt Las Vegas?", answer: "Nevada" },
  { id: 172, category: "Geografie", question: "Wie heißt die Hauptstadt von Kanada?", answer: "Ottawa" },
  { id: 173, category: "Geografie", question: "Welches asiatische Land wird auch als 'Land der aufgehenden Sonne' bezeichnet?", answer: "Japan" },
  { id: 174, category: "Geografie", question: "Wie heißt das größte Korallenriff der Erde?", answer: "Great Barrier Reef" },
  { id: 175, category: "Geografie", question: "Welches Gebirge erstreckt sich über den Norden Italiens, die Schweiz und Österreich?", answer: "Alpen" },
  { id: 176, category: "Geografie", question: "Was ist das bevölkerungsreichste Land in Afrika?", answer: "Nigeria" },
  { id: 177, category: "Geografie", question: "An welchem See liegt die Stadt Konstanz?", answer: "Bodensee" },
  { id: 178, category: "Geografie", question: "Wie heißt die Hauptstadt von China?", answer: "Peking (Beijing)" },
  { id: 179, category: "Geografie", question: "Welches Land hat die Form eines Stiefels?", answer: "Italien" },
  { id: 180, category: "Geografie", question: "Wie heißt die Meerenge zwischen Spanien und Marokko?", answer: "Straße von Gibraltar" },
  { id: 181, category: "Geografie", question: "Welche US-Metropole wird auch als 'The Big Apple' bezeichnet?", answer: "New York City" },
  { id: 182, category: "Geografie", question: "Was ist der trockenste Ort (Wüste) der Erde?", answer: "Atacama-Wüste" },
  { id: 183, category: "Geografie", question: "Wie heißt die Hauptstadt von Ägypten?", answer: "Kairo" },
  { id: 184, category: "Geografie", question: "Welche Inselgruppe im Atlantischen Ozean gehört geografisch zu Afrika, aber politisch zu Spanien?", answer: "Kanarische Inseln" },
  { id: 185, category: "Geografie", question: "Durch welches europäische Land fließt die Seine?", answer: "Frankreich" },
  { id: 186, category: "Geografie", question: "Wie heißt die Hauptstadt von Russland?", answer: "Moskau" },
  { id: 187, category: "Geografie", question: "Welches Land hat das Autokennzeichen 'CH'?", answer: "Schweiz (Confoederatio Helvetica)" },
  { id: 188, category: "Geografie", question: "Wie heißt die Hauptstadt von Japan?", answer: "Tokio" },
  { id: 189, category: "Geografie", question: "Welches Meer grenzt an die nördliche Küste Deutschlands?", answer: "Nordsee und Ostsee" },
  { id: 190, category: "Geografie", question: "Welcher Berg ist der höchste Berg Deutschlands?", answer: "Zugspitze" },
  { id: 191, category: "Geografie", question: "Wie heißt die Hauptstadt der Türkei?", answer: "Ankara" },
  { id: 192, category: "Geografie", question: "Welches Land besitzt die meisten natürlichen Seen der Welt?", answer: "Kanada" },
  { id: 193, category: "Geografie", question: "Wie heißt der größte Fluss Afrikas?", answer: "Nil" },
  { id: 194, category: "Geografie", question: "In welchem Land liegt das Opernhaus von Sydney?", answer: "Australien" },
  { id: 195, category: "Geografie", question: "Welche Insel im Mittelmeer ist zweigeteilt in einen griechischen und einen türkischen Sektor?", answer: "Zypern" },
  { id: 196, category: "Geografie", question: "Wie heißt die Hauptstadt von Schweden?", answer: "Stockholm" },
  { id: 197, category: "Geografie", question: "An welchem Fluss liegt die ungarische Hauptstadt Budapest?", answer: "Donau" },
  { id: 198, category: "Geografie", question: "Welcher Ozean trennt Amerika von Europa?", answer: "Atlantischer Ozean" },
  { id: 199, category: "Geografie", question: "Welche Wüste erstreckt sich über den Norden Afrikas?", answer: "Sahara" },
  { id: 200, category: "Geografie", question: "Wie heißt die Hauptstadt von Griechenland?", answer: "Athen" },
  { id: 201, category: "Geografie", question: "In welchem Land liegt die Provinz Bayern?", answer: "Deutschland" },
  { id: 202, category: "Geografie", question: "Welches Land grenzt im Süden direkt an die USA?", answer: "Mexiko" },
  { id: 203, category: "Geografie", question: "Was ist die Hauptstadt von Irland?", answer: "Dublin" },
  { id: 204, category: "Geografie", question: "Welche Stadt gilt als Hauptstadt von Nordirland?", answer: "Belfast" },
  { id: 205, category: "Geografie", question: "Welches Land hat die größte Fläche in Südamerika?", answer: "Brasilien" },
  { id: 206, category: "Geografie", question: "Wie heißt die Hauptstadt von Norwegen?", answer: "Oslo" },
  { id: 207, category: "Geografie", question: "Wie heißt die nördlichste Hauptstadt der Welt?", answer: "Reykjavík (Island)" },
  { id: 208, category: "Geografie", question: "In welchem Land entspringt der Fluss Rhein?", answer: "Schweiz" },
  { id: 209, category: "Geografie", question: "Welches asiatische Land ist flächenmäßig das größte, das komplett in Asien liegt (ohne Russland)?", answer: "China" },
  { id: 210, category: "Geografie", question: "Wie heißt die Hauptstadt von Österreich?", answer: "Wien" },
  { id: 211, category: "Geografie", question: "Welche polnische Stadt an der Weichsel war früher die Hauptstadt des Landes?", answer: "Krakau" },
  { id: 212, category: "Geografie", question: "In welchem Land befindet sich die Region Katalonien?", answer: "Spanien" },
  { id: 213, category: "Geografie", question: "Wie heißt das flächenmäßig größte Land Afrikas?", answer: "Algerien" },
  { id: 214, category: "Geografie", question: "Wie heißt der Vulkan, der Island im Jahr 2010 lahmgelegt hat?", answer: "Eyjafjallajökull" },
  { id: 215, category: "Geografie", question: "Welche Stadt liegt am Bosporus und erstreckt sich über zwei Kontinente?", answer: "Istanbul" },
  { id: 216, category: "Geografie", question: "Was ist die Hauptstadt der USA?", answer: "Washington, D.C." },
  { id: 217, category: "Geografie", question: "Welcher Fluss fließt durch Paris?", answer: "Seine" },
  { id: 218, category: "Geografie", question: "In welchem Land liegt die weltberühmte Halbinsel Krim?", answer: "Ukraine" },
  { id: 219, category: "Geografie", question: "Welches europäische Land grenzt im Westen an Spanien?", answer: "Portugal" },
  { id: 220, category: "Geografie", question: "Wie heißt der tiefste See der Erde?", answer: "Baikalsee" },
  { id: 221, category: "Geografie", question: "Was ist die Hauptstadt von Indien?", answer: "Neu-Delhi" },
  { id: 222, category: "Geografie", question: "Welcher Berg ist der höchste Berg Afrikas?", answer: "Kilimandscharo" },
  { id: 223, category: "Geografie", question: "Wie heißt das größte Land Nordamerikas?", answer: "Kanada" },
  { id: 224, category: "Geografie", question: "Welches Meer grenzt an die Strände von Tel Aviv?", answer: "Mittelmeer" },
  { id: 225, category: "Geografie", question: "Wie heißt die Hauptstadt von Thailand?", answer: "Bangkok" },
  { id: 226, category: "Geografie", question: "Wie heißt der höchste Berg der Alpen?", answer: "Mont Blanc" },
  { id: 227, category: "Geografie", question: "Welches skandinavische Land grenzt direkt an Russland und Schweden?", answer: "Finnland" },
  { id: 228, category: "Geografie", question: "Was ist die Hauptstadt von Island?", answer: "Reykjavík" },
  { id: 229, category: "Geografie", question: "An welchem Fluss liegt das berühmte Schloss Neuschwanstein (Kanton/Region)?", answer: "Lech (in der Nähe von Füssen/Allgäu)" },
  { id: 230, category: "Geografie", question: "In welchem Ozean liegen die Malediven?", answer: "Indischer Ozean" },
  { id: 231, category: "Geografie", question: "Welcher Staat ist der flächenmäßig kleinste der USA?", answer: "Rhode Island" },
  { id: 232, category: "Geografie", question: "Wie heißt die Hauptstadt von Kroatien?", answer: "Zagreb" },
  { id: 233, category: "Geografie", question: "Welches europäische Land besteht aus über 6.000 Inseln?", answer: "Griechenland" },
  { id: 234, category: "Geografie", question: "Wie heißt der größte Bundesstaat der USA nach Fläche?", answer: "Alaska" },
  { id: 235, category: "Geografie", question: "In welchem afrikanischen Land liegt die Hafenstadt Kapstadt?", answer: "Südafrika" },
  { id: 236, category: "Geografie", question: "Wie heißt der Fluss, der durch die Stadt Prag fließt?", answer: "Moldau" },
  { id: 237, category: "Geografie", question: "In welchem Land liegt der See Genezareth?", answer: "Israel" },
  { id: 238, category: "Geografie", question: "Wie heißt die Hauptstadt von Dänemark?", answer: "Kopenhagen" },
  { id: 239, category: "Geografie", question: "Was ist der südlichste bewohnte Kontinent der Erde?", answer: "Südamerika" },
  { id: 240, category: "Geografie", question: "Welches asiatische Land besitzt die Region Tibet?", answer: "China" },

  // GAMING (241-320)
  { id: 241, category: "Gaming", question: "Aus welchem Videospiel stammt der grüne Held Link?", answer: "The Legend of Zelda" },
  { id: 242, category: "Gaming", question: "Was ist das meistverkaufte Videospiel aller Zeiten?", answer: "Minecraft" },
  { id: 243, category: "Gaming", question: "Welche Farbe hat das Logo von PlayStation üblicherweise?", answer: "Blau (oder Weiß)" },
  { id: 244, category: "Gaming", question: "Wie heißt der Bruder des berühmten Klempners Mario?", answer: "Luigi" },
  { id: 245, category: "Gaming", question: "Welches ikonische Klötzchenspiel wurde vom Russen Alexei Paschitnow erfunden?", answer: "Tetris" },
  { id: 246, category: "Gaming", question: "Aus welchem Videospiel stammt die Archäologin Lara Croft?", answer: "Tomb Raider" },
  { id: 247, category: "Gaming", question: "Wie heißt das gelbe Pixelmonster, das Punkte frisst und Geistern ausweicht?", answer: "Pac-Man" },
  { id: 248, category: "Gaming", question: "Welche Firma stellt die Konsolen-Reihe 'Switch' her?", answer: "Nintendo" },
  { id: 249, category: "Gaming", question: "In welchem MMORPG erkunden Spieler die Fantasy-Welt Azeroth?", answer: "World of Warcraft" },
  { id: 250, category: "Gaming", question: "Wie heißt der Hauptcharakter aus der Halo-Reihe?", answer: "Master Chief" },
  { id: 251, category: "Gaming", question: "Welcher Survival-Shooter erfand das 'Battle Royale'-Genre entscheidend mit (Abkürzung)?", answer: "PUBG (PlayerUnknown's Battlegrounds)" },
  { id: 252, category: "Gaming", question: "Welches extrem erfolgreiche Battle-Royale-Spiel von Epic Games startete 2017?", answer: "Fortnite" },
  { id: 253, category: "Gaming", question: "Welches Brettspiel dreht sich um den Kauf von Grundstücken und Straßen?", answer: "Monopoly" },
  { id: 254, category: "Gaming", question: "Wie heißt die Hauptfigur in der 'Witcher'-Videospielreihe?", answer: "Geralt von Riva" },
  { id: 255, category: "Gaming", question: "Welche Gaming-Plattform wird von der Firma Valve betrieben?", answer: "Steam" },
  { id: 256, category: "Gaming", question: "Aus welchem Rennspiel von Nintendo stammen Strecken wie der 'Regenbogen-Boulevard'?", answer: "Mario Kart" },
  { id: 257, category: "Gaming", question: "In welchem Sandbox-Spiel kann man virtuelle Häuser bauen und Lebensgeschichten steuern?", answer: "Die Sims" },
  { id: 258, category: "Gaming", question: "Welches beliebte Kartenspiel wird mit Sonderkarten wie 'Zwei Ziehen' und 'Retour' gespielt?", answer: "UNO" },
  { id: 259, category: "Gaming", question: "Wie lautet der Name des blauen Igels, der SEGAs Maskottchen ist?", answer: "Sonic (the Hedgehog)" },
  { id: 260, category: "Gaming", question: "In welchem Open-World-Spiel treibt man im fiktiven Staat San Andreas sein Unwesen (Abkürzung)?", answer: "GTA (Grand Theft Auto)" },
  { id: 261, category: "Gaming", question: "Welche Taschenmonster fängt man im gleichnamigen RPG mit Pokebällen?", answer: "Pokémon" },
  { id: 262, category: "Gaming", question: "Welcher Spieletitel von Riot Games ist eines der größten E-Sports-MOBA-Spiele weltweit (Abkürzung)?", answer: "LoL (League of Legends)" },
  { id: 263, category: "Gaming", question: "Wie heißt der fiktive Pilz-Königreich-Bösewicht, der Prinzessin Peach entführt?", answer: "Bowser" },
  { id: 264, category: "Gaming", question: "Aus welchem Spiel stammt der Ausruf 'Praise the Sun'?", answer: "Dark Souls" },
  { id: 265, category: "Gaming", question: "Wie heißt die künstliche Intelligenz, die Portal-Spieler mit Kuchen ködert?", answer: "GLaDOS" },
  { id: 266, category: "Gaming", question: "Welches klassische asiatische Brettspiel wird mit schwarzen und weißen Steinen auf einem Gitternetz gespielt?", answer: "Go" },
  { id: 267, category: "Gaming", question: "In welchem Detektiv-Partyspiel müssen Bürger die Werwölfe entlarven?", answer: "Werwölfe von Düsterwald" },
  { id: 268, category: "Gaming", question: "Wie heißt die Währung im Spiel Fallout?", answer: "Kronkorken (Bottle caps)" },
  { id: 269, category: "Gaming", question: "Welches Studio entwickelte 'Cyberpunk 2077' und 'The Witcher 3'?", answer: "CD Projekt Red" },
  { id: 270, category: "Gaming", question: "Aus welchem schwedischen Hause stammt die Spiele-Engine 'Frostbite'?", answer: "DICE" },
  { id: 271, category: "Gaming", question: "Welche Videospielreihe führt uns in den Kampf zwischen Templern und Assassinen?", answer: "Assassin's Creed" },
  { id: 272, category: "Gaming", question: "Welches legendäre Spielzeug-Franchise brachte Pokémon hervor?", answer: "Nintendo / Game Freak" },
  { id: 273, category: "Gaming", question: "Wie heißt das Action-Rollenspiel von Blizzard Entertainment, dessen vierter Teil 2023 erschien?", answer: "Diablo" },
  { id: 274, category: "Gaming", question: "In welchem Spiel baut man als Siedler Straßen, Dörfer und sammelt Rohstoffe wie Wolle und Erz?", answer: "Die Siedler von Catan (Catan)" },
  { id: 275, category: "Gaming", question: "Welcher Indie-Hit lässt den Spieler einen Farmer im Sternentautal spielen?", answer: "Stardew Valley" },
  { id: 276, category: "Gaming", question: "Welcher Held aus God of War metzelt sich erst durch die griechische, dann durch die nordische Mythologie?", answer: "Kratos" },
  { id: 277, category: "Gaming", question: "Aus welchem Nintendo-Prügelspiel stammen Charaktere wie Kirby, Fox und Samus?", answer: "Super Smash Bros." },
  { id: 278, category: "Gaming", question: "Wie nennt man im E-Sport-Jargon ein Spiel, bei dem man aus der Ego-Perspektive schießt (Abkürzung)?", answer: "FPS (First-Person Shooter / Ego-Shooter)" },
  { id: 279, category: "Gaming", question: "In welchem Spiel fliegt ein fliegender Bus Spieler über eine Insel, um zu looten und zu überleben?", answer: "Fortnite" },
  { id: 280, category: "Gaming", question: "Welches klassische Kartenspiel hat Varianten wie Texas Hold'em?", answer: "Poker" },
  { id: 281, category: "Gaming", question: "Wie heißt das fliegende Fabelwesen, das in 'Minecraft' im Ende besiegt werden muss?", answer: "Enderdrache (Ender Dragon)" },
  { id: 282, category: "Gaming", question: "Welches weltberühmte Weltraum-RPG-Franchise von BioWare hat Commander Shepard als Protagonisten?", answer: "Mass Effect" },
  { id: 283, category: "Gaming", question: "Aus welchem kooperativen Kochspiel fliegt einem ständig die Küche um die Ohren?", answer: "Overcooked" },
  { id: 284, category: "Gaming", question: "Welcher Bösewicht ist Marios Erzfeind?", answer: "Bowser" },
  { id: 285, category: "Gaming", question: "Wie heißt das Western-Epos von Rockstar Games um Arthur Morgan?", answer: "Red Dead Redemption 2" },
  { id: 286, category: "Gaming", question: "In welchem Shooter von Valve spielt man Antiterror-Einheiten gegen Terroristen (Abkürzung)?", answer: "CS:GO / Counter-Strike" },
  { id: 287, category: "Gaming", question: "Welches Brettspiel fordert Spieler heraus, global ausbrechende Epidemien zu bekämpfen?", answer: "Pandemic" },
  { id: 288, category: "Gaming", question: "Aus welchem Stealth-Spiel stammt der glatzköpfige Killer 'Agent 47'?", answer: "Hitman" },
  { id: 289, category: "Gaming", question: "Welche schwedische Entwicklergruppe schuf Minecraft?", answer: "Mojang" },
  { id: 290, category: "Gaming", question: "Aus welchem Horrorspiel stammt die berühmte Krankenschwester-Figur (Nurse)?", answer: "Silent Hill" },
  { id: 291, category: "Gaming", question: "Welches klassische PC-Echtzeitstrategiespiel stammt von Westwood Studios und handelt von GDI gegen Nod?", answer: "Command & Conquer" },
  { id: 292, category: "Gaming", question: "In welchem Spiel muss man als Affe Ballons mit Pfeilen zerplatzen lassen?", answer: "Bloons TD" },
  { id: 293, category: "Gaming", question: "Welche Rennspielreihe von EA ist berühmt für illegale Straßenrennen und Polizeijagden?", answer: "Need for Speed" },
  { id: 294, category: "Gaming", question: "Aus welchem Videospiel stammt der Satz 'A man chooses, a slave obeys'?", answer: "BioShock" },
  { id: 295, category: "Gaming", question: "Welcher Klassiker gilt als das erste kommerziell erfolgreiche Videospiel?", answer: "Pong" },
  { id: 296, category: "Gaming", question: "In welchem Aufbauspiel besiedelt man eine historische Epoche und interagiert mit Händlern (z.B. 1800)?", answer: "Anno" },
  { id: 297, category: "Gaming", question: "Welches bunte Party-Hindernislaufspiel mit bohnenartigen Figuren wurde 2020 zum Riesenhit?", answer: "Fall Guys" },
  { id: 298, category: "Gaming", question: "In welchem MMORPG gibt es die Gildenallianzen 'Allianz' und 'Horde'?", answer: "World of Warcraft" },
  { id: 299, category: "Gaming", question: "Welche Spielfigur reist mit einem pelzigen Sidekick namens Daxter?", answer: "Jak (Jak and Daxter)" },
  { id: 300, category: "Gaming", question: "Wie heißt das Kartenspiel im Witcher-Universum, das als eigenständiges Spiel ausgekoppelt wurde?", answer: "Gwent" },
  { id: 301, category: "Gaming", question: "Aus welchem Spiel stammt die Zitatzeile: 'The cake is a lie'?", answer: "Portal" },
  { id: 302, category: "Gaming", question: "Welche Handheld-Konsole von Nintendo aus dem Jahr 1989 revolutionierte das mobile Gaming?", answer: "Game Boy" },
  { id: 303, category: "Gaming", question: "Welches kooperative Survival-Spiel lässt Spieler als Wikinger in einer nordischen Fegefeuer-Welt überleben?", answer: "Valheim" },
  { id: 304, category: "Gaming", question: "Aus welchem Ego-Shooter stammt der Feindtyp namens 'Creeper'?", answer: "Minecraft (obwohl Sandbox, Creeper sind legendär)" },
  { id: 305, category: "Gaming", question: "Wie heißt das Strategiespiel, bei dem man ein Volk von der Steinzeit bis in die Moderne führt?", answer: "Civilization" },
  { id: 306, category: "Gaming", question: "Welches bunte Hüpfspiel von Nintendo führt den Spieler auf eine tropische Insel voller Bananen?", answer: "Donkey Kong" },
  { id: 307, category: "Gaming", question: "Aus welchem Kult-Shooter von id Software stammt das Waffenmonster 'BFG 9000'?", answer: "DOOM" },
  { id: 308, category: "Gaming", question: "Wie heißt das Action-Adventure von Sony, in dem Ellie und Joel in einer postapokalyptischen Welt ums Überleben kämpfen?", answer: "The Last of Us" },
  { id: 309, category: "Gaming", question: "In welchem Spiel von InnerSloth müssen Crewmitglieder den Hochstapler (Impostor) finden?", answer: "Among Us" },
  { id: 310, category: "Gaming", question: "Aus welchem Rollenspiel stammt die legendäre Diebesgilde von Rifton?", answer: "Skyrim (The Elder Scrolls V)" },
  { id: 311, category: "Gaming", question: "Wie heißt das kooperative Zwergenspiel, bei dem man Mineralien abbaut und Alien-Bugs bekämpft?", answer: "Deep Rock Galactic" },
  { id: 312, category: "Gaming", question: "In welchem Rennspiel kickt man mit ferngesteuerten Autos einen Riesenball ins Tor?", answer: "Rocket League" },
  { id: 313, category: "Gaming", question: "Aus welchem Spiel stammt die Figur des 'John Marston'?", answer: "Red Dead Redemption" },
  { id: 314, category: "Gaming", question: "Welche Konsole von Microsoft konkurriert direkt mit Sonys PlayStation?", answer: "Xbox" },
  { id: 315, category: "Gaming", question: "Welches kooperative Spiel von Hazelight Studios gewann 2021 den 'Game of the Year'-Award?", answer: "It Takes Two" },
  { id: 316, category: "Gaming", question: "Aus welchem Pixel-Rollenspiel stammt die charmant-gruselige Unterwelt voller Monster (Sans, Papyrus)?", answer: "Undertale" },
  { id: 317, category: "Gaming", question: "Welches populäre PC-Strategiespiel von Blizzard spielt im Weltraum und dreht sich um Terraner, Zerg und Protoss?", answer: "StarCraft" },
  { id: 318, category: "Gaming", question: "Wie heißt der pelzige Beuteldachs, der das Maskottchen der ersten PlayStation war?", answer: "Crash Bandicoot" },
  { id: 319, category: "Gaming", question: "Welche Firma zeichnet für Klassiker wie Pac-Man, Tekken und Dark Souls verantwortlich?", answer: "Bandai Namco" },
  { id: 320, category: "Gaming", question: "In welchem Spiel erntet man als kleiner gelber Traktor Getreide?", answer: "Landwirtschafts-Simulator" },

  // TRIVIA (321-400)
  { id: 321, category: "Trivia", question: "Welches Tier schläft im Stehen und hat Hufe?", answer: "Pferd (oder Esel)" },
  { id: 322, category: "Trivia", question: "Wie viele Sekunden hat eine Stunde?", answer: "3600" },
  { id: 323, category: "Trivia", question: "Welches Meerrettichgewächs ist extrem scharf und typisch für die japanische Küche?", answer: "Wasabi" },
  { id: 324, category: "Trivia", question: "Wie viele Punkte hat ein Standard-Würfel insgesamt auf allen Seiten?", answer: "21" },
  { id: 325, category: "Trivia", question: "Aus welchem Land stammt der berühmte Feta-Käse?", answer: "Griechenland" },
  { id: 326, category: "Trivia", question: "Welches Land hat die größte Anzahl an aktiven Vulkanen der Welt?", answer: "Indonesien" },
  { id: 327, category: "Trivia", question: "Welches Tier kann seine Augen unabhängig voneinander bewegen?", answer: "Chamäleon" },
  { id: 328, category: "Trivia", question: "Wie viele Streifen hat das Logo von Adidas?", answer: "3" },
  { id: 329, category: "Trivia", question: "Was ist das Hauptnahrungsmittel eines Koalabären?", answer: "Eukalyptus" },
  { id: 330, category: "Trivia", question: "Welches Land konsumiert pro Kopf die meiste Schokolade weltweit?", answer: "Schweiz" },
  { id: 331, category: "Trivia", question: "Wie viele Tastengrade/Tasten hat ein Standardklavier?", answer: "88" },
  { id: 332, category: "Trivia", question: "Welche Kaffeespezialität hat einen Namen, der übersetzt 'gefleckte Milch' bedeutet?", answer: "Latte Macchiato" },
  { id: 333, category: "Trivia", question: "Welches Säugetier kann als einziges aktiv fliegen?", answer: "Fledermaus" },
  { id: 334, category: "Trivia", question: "Wie viele Farben hat die deutsche Flagge?", answer: "3" },
  { id: 335, category: "Trivia", question: "Aus welchem Material bestehen die Stoßzähne von Elefanten?", answer: "Elfenbein" },
  { id: 336, category: "Trivia", question: "Welches Organ im menschlichen Körper verbraucht am meisten Energie?", answer: "Das Gehirn" },
  { id: 337, category: "Trivia", question: "Welches Tier ist bekannt dafür, den Kopf bei Gefahr in den Sand zu stecken (auch wenn das ein Mythos ist)?", answer: "Strauß" },
  { id: 338, category: "Trivia", question: "Wie viele Sterne hat die Flagge der Europäischen Union?", answer: "12" },
  { id: 339, category: "Trivia", question: "Was ist das chemische Symbol für Eisen?", answer: "Fe" },
  { id: 340, category: "Trivia", question: "Welches Land erfand die Pizza?", answer: "Italien" },
  { id: 341, category: "Trivia", question: "Wie viele Atemzüge macht ein Mensch durchschnittlich pro Minute im Ruhezustand?", answer: "Ca. 12 bis 18" },
  { id: 342, category: "Trivia", question: "Welches Tier gilt als das schnellste Landtier der Welt?", answer: "Gepard" },
  { id: 343, category: "Trivia", question: "Wie viele Gramm sind ein Kilogramm?", answer: "1000" },
  { id: 344, category: "Trivia", question: "Welches Tier hat die längste Tragzeit aller Säugetiere?", answer: "Elefant (ca. 22 Monate)" },
  { id: 345, category: "Trivia", question: "Was ist das chemische Symbol für Kohlenstoff?", answer: "C" },
  { id: 346, category: "Trivia", question: "Aus welchem Getreide wird Bier traditionell hauptsächlich gebraut?", answer: "Gerste (Malz)" },
  { id: 347, category: "Trivia", question: "Welches Tier hat die längste Zunge im Verhältnis zu seiner Körpergröße?", answer: "Chamäleon" },
  { id: 348, category: "Trivia", question: "Wie viele Tasten hat eine Computer-Tastatur im Standard-QWERTZ-Layout ungefähr?", answer: "102 bis 105" },
  { id: 349, category: "Trivia", question: "Welches vitaminreiche Gemüse schützt Seefahrer traditionell vor Skorbut?", answer: "Zitrone / Sauerkraut (Vitamin C)" },
  { id: 350, category: "Trivia", question: "Welches Metall ist bei Raumtemperatur flüssig?", answer: "Quecksilber" },
  { id: 351, category: "Trivia", question: "Aus welchem Land stammt das berühmte Nationalgericht 'Poutine'?", answer: "Kanada" },
  { id: 352, category: "Trivia", question: "Wie viele Spieler befinden sich beim Eishockey maximal gleichzeitig auf dem Eis (pro Team)?", answer: "6" },
  { id: 353, category: "Trivia", question: "Welches Tier besitzt blaues Blut?", answer: "Krake / Tintenfisch" },
  { id: 354, category: "Trivia", question: "Wie viele Knochen befinden sich im menschlichen Ohr?", answer: "3 (Hammer, Amboss, Steigbügel)" },
  { id: 355, category: "Trivia", question: "Aus welcher Knolle wird Zucker in Europa hauptsächlich gewonnen?", answer: "Zuckerrübe" },
  { id: 356, category: "Trivia", question: "Welches Tier hat den stärksten Biss im Verhältnis zu seiner Körpergröße?", answer: "Piranha / Tasmanischer Teufel" },
  { id: 357, category: "Trivia", question: "Wie viele Zeitzonen gibt es auf der Erde?", answer: "24" },
  { id: 358, category: "Trivia", question: "Aus welchem Land stammt das weltbekannte Croissant ursprünglich?", answer: "Österreich (Wien)" },
  { id: 359, category: "Trivia", question: "Welches Tier schläft fast 20 Stunden am Tag?", answer: "Koala / Faultier" },
  { id: 360, category: "Trivia", question: "Was ist das chemische Symbol für Silber?", answer: "Ag" },
  { id: 361, category: "Trivia", question: "Wie viele Knochen hat das Skelett einer Katze ungefähr?", answer: "Ca. 230" },
  { id: 362, category: "Trivia", question: "Welche Frucht besteht zu fast 92 Prozent aus Wasser?", answer: "Wassermelone" },
  { id: 363, category: "Trivia", question: "Welche Farbe hat flüssiger Sauerstoff?", answer: "Hellblau" },
  { id: 364, category: "Trivia", question: "Wie viele Millimeter hat ein Meter?", answer: "1000" },
  { id: 365, category: "Trivia", question: "Aus welchem Tier wird echter Kaviar gewonnen?", answer: "Stör" },
  { id: 366, category: "Trivia", question: "Welches Tier hat die größten Augen aller bekannten Lebewesen?", answer: "Riesenkalmar" },
  { id: 367, category: "Trivia", question: "Wie viele Räder hat ein normales Einrad?", answer: "1" },
  { id: 368, category: "Trivia", question: "Was ist das Hauptnahrungsmittel eines Großen Pandas?", answer: "Bambus" },
  { id: 369, category: "Trivia", question: "Welches Tier kann theoretisch unendlich lange leben (biologische Unsterblichkeit)?", answer: "Turritopsis dohrnii (unsterbliche Qualle)" },
  { id: 370, category: "Trivia", question: "Was ist das chemische Symbol für Stickstoff?", answer: "N" },
  { id: 371, category: "Trivia", question: "Wie viele Grade hat ein rechter Winkel?", answer: "90" },
  { id: 372, category: "Trivia", question: "Aus welchem Land stammt die Delikatesse 'Trüffel' am bekanntesten?", answer: "Frankreich und Italien" },
  { id: 373, category: "Trivia", question: "Welches Tier besitzt das lauteste Organ aller Lebewesen?", answer: "Pottwal" },
  { id: 374, category: "Trivia", question: "Wie viele Kilo wiegt ein Liter reines Wasser bei 4 Grad Celsius?", answer: "1" },
  { id: 375, category: "Trivia", question: "Was ist das chemische Symbol für Helium?", answer: "He" },
  { id: 376, category: "Trivia", question: "Aus welchem Land stammt der weltbekannte Cheddar-Käse?", answer: "Großbritannien (England)" },
  { id: 377, category: "Trivia", question: "Welches Tier hat im Verhältnis zu seinem Gehirn die größten Augen?", answer: "Koboldmaki" },
  { id: 378, category: "Trivia", question: "Wie viele Ringe hat das offizielle Logo der Olympischen Spiele?", answer: "5" },
  { id: 379, category: "Trivia", question: "Welches Tier gilt als das intelligenteste wirbellose Tier?", answer: "Oktopus" },
  { id: 380, category: "Trivia", question: "Welches Land hat die größte Kakao-Produktion weltweit?", answer: "Elfenbeinküste" },
  { id: 381, category: "Trivia", question: "Wie viele Jahre dauert ein Jahrzehnt?", answer: "10" },
  { id: 382, category: "Trivia", question: "Welche Frucht enthält das Enzym Bromelain, das Proteine spaltet?", answer: "Ananas" },
  { id: 383, category: "Trivia", question: "Welche Farbe hat der Farbstoff Chlorophyll in Pflanzen?", answer: "Grün" },
  { id: 384, category: "Trivia", question: "Wie viele Milliliter passen in eine standardmäßige Kaffeetasse?", answer: "Ca. 150 bis 250 ml" },
  { id: 385, category: "Trivia", question: "Aus welchem Land stammt das scharfe rote Gewürz Kimchi?", answer: "Südkorea" },
  { id: 386, category: "Trivia", question: "Welches Säugetier legt Eier, obwohl es seine Jungen säugt?", answer: "Schnabeltier (Platypus)" },
  { id: 387, category: "Trivia", question: "Wie viele Spielfelder hat ein klassisches Schachbrett?", answer: "64" },
  { id: 388, category: "Trivia", question: "Welches Tier hat das dichteste Fell aller bekannten Lebewesen?", answer: "Seeotter" },
  { id: 389, category: "Trivia", question: "What is the chemical symbol for Oxygen?", answer: "O" },
  { id: 390, category: "Trivia", question: "Aus welchem Land stammt die Hunderasse Husky ursprünglich?", answer: "Sibirien / Russland" },
  { id: 391, category: "Trivia", question: "Wie viele Spieler befinden sich beim Volleyball pro Mannschaft auf dem Feld?", answer: "6" },
  { id: 392, category: "Trivia", question: "Welche Frucht wächst an einer Palme und liefert Milch sowie Öl?", answer: "Kokosnuss" },
  { id: 393, category: "Trivia", question: "Welche Farbe hat der Planet Mars wegen seines hohen Eisenoxid-Anteils?", answer: "Rot" },
  { id: 394, category: "Trivia", question: "Wie viele Milligramm sind ein Gramm?", answer: "1000" },
  { id: 395, category: "Trivia", question: "Aus welchem Tier wird echtes Angorawolle gewonnen?", answer: "Angorakaninchen" },
  { id: 396, category: "Trivia", question: "Welches Tier kann am längsten ohne Wasser überleben?", answer: "Kängururatte (noch länger als Kamele)" },
  { id: 397, category: "Trivia", question: "Wie viele Tasten hat eine handelsübliche Flöte (Blockflöte) normalerweise an Grifflöchern?", answer: "8" },
  { id: 398, category: "Trivia", question: "Welches Tier besitzt die stärkste Säure im Magen, die sogar Metall auflösen kann?", answer: "Bartgeier" },
  { id: 399, category: "Trivia", question: "Was ist das chemische Symbol für Kupfer?", answer: "Cu" },
  { id: 400, category: "Trivia", question: "Aus welchem Land stammt der Nationaltanz Flamenco?", answer: "Spanien" }
];
